# Generated by Django 2.1.3 on 2018-12-05 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heatster', '0002_auto_20181202_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valve',
            name='set_temp',
        ),
        migrations.AlterField(
            model_name='valve',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='heatster.Room'),
        ),
    ]
