# Generated by Django 2.1.3 on 2018-11-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heatster', '0002_auto_20181121_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_id',
            new_name='id',
        ),
    ]
