# Generated by Django 2.1.3 on 2018-12-05 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heatster', '0004_auto_20181205_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valve',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_id', to='heatster.Room'),
        ),
    ]
