# Generated by Django 2.1.3 on 2018-11-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatster', '0004_auto_20181121_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='hour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
