# Generated by Django 2.1.3 on 2018-11-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatster', '0005_schedule_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_temp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='set_temp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valve',
            name='set_temp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
