# Generated by Django 2.1.3 on 2018-12-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heatster', '0006_auto_20181205_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valve',
            old_name='room',
            new_name='room_id',
        ),
    ]
