# Generated by Django 2.1.3 on 2018-11-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatster', '0007_auto_20181125_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='sleep_temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='vacation_temp',
            field=models.FloatField(),
        ),
    ]
