# Generated by Django 2.1.3 on 2018-12-06 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heatster', '0008_auto_20181205_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='weekday_id',
        ),
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='heatster.Room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='weekday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weekday', to='heatster.Weekday'),
            preserve_default=False,
        ),
    ]
