# Generated by Django 2.1.3 on 2018-12-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heatster', '0010_room_valve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='valve',
        ),
    ]
