# Generated by Django 2.1.3 on 2018-12-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatster', '0011_remove_room_valve'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='valve',
            field=models.ManyToManyField(related_name='_room_valve_+', to='heatster.Valve'),
        ),
    ]
